# Use root/example as user/password credentials

services:
  database:
    image: mysql:9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootdocker
      MYSQL_DATABASE: marloy

    ports:
      - "3308:3306"
    volumes:
     - mysql_data:/var/lib/mysql
     - ./db_init:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend:/app
    working_dir: /app
    command: python app.py

volumes:
  mysql_data:
